# All About Basic Tensor Operations in PyTorch

### Tensor is a multi-dimensional matrix containing a single data type

Here are a few selected PyTorch tensor methods  
- new_full: Used to create a tensor with specified fill value
- abs: Each element of the tensor is converted to an absoulute value
- add: Adds either a scalar or a tensor to a tensor
- matmul: multiplication of tensors
- eq: Checks two tensors for equality based on each element

In [0]:
# Import torch and other required modules
import torch

## Function 1 - torch.new_full (size, fill_value, dtype=None, device=None, requires_grad=False)) --> Tensor

This method is used to return a tensor with specified fill value

In [15]:
#Example 1.1
tensor = torch.tensor([[1,2], [3,4]])
tensor.new_full((2,2), 0)

tensor([[0, 0],
        [0, 0]])

In the above example tensor is filled with zeros.

In [21]:
#Example 1.2
tensor = torch.ones(())
tensor.new_full((2,2,2), True, dtype=bool,device=None,requires_grad=False)

tensor([[[True, True],
         [True, True]],

        [[True, True],
         [True, True]]])

Here is an example where an empty tensor is initiated to (m,n,o) dimensions and with value True. Note that if you do not specify dtype the value is initiated as float value 1. even though you specified True.

In [38]:
# Example 1.3 - breaking (to illustrate when it breaks)
tensor = torch.tensor([[1,2], [3,4]], dtype=int)
tensor.new_full((2,2),1.5)
tensor
# tensor.type() 
# Type still shows as LongTensor

tensor([[1, 2],
        [3, 4]])

Note that in the above example we were not able to use fill value of float for a tensor which was declared as int.

new_full is a useful function alongwith other family of new_ functions including new_tensor and new_empty. These functions are used to create tensors with similar dtype as original but possibly different dimensions.

## Function 2 - abs () --> Tensor

This function is used to return a tensor with absolute value element by element

In [42]:
# Example 2.1
tensor= torch.tensor([[-1,-2],[3,0]])
tensor.abs()

tensor([[1, 2],
        [3, 0]])

In the above example negative values are converted to positive and positive (and 0) are left intact.

In [44]:
# Example 2.2
tensor = torch.tensor([[1.5,2.5],[-79.1,0]])
tensor.abs()

tensor([[ 1.5000,  2.5000],
        [79.1000,  0.0000]])

As expected this works for float as well.

In [45]:
# Example 2.3 Not working
tensor = torch.tensor([[False,False],[True,True]])
tensor.abs()

RuntimeError: ignored

Does not work for float

As in most programming languages, abs() is a handy function implemented for tensor in PyTorch.

## Function 3 - add(input, other, *, alpha=1, out=None) --> Tensor

This function is used to add two tensors or add a scalar to a tensor.

In [47]:
# Example 3.1
t1 = torch.tensor([.12,.34,.56,.78])
torch.add(t1,1)
#t1.add(1)

tensor([1.1200, 1.3400, 1.5600, 1.7800])

In the above example we added scalar value of 1 to tensor t1

In [52]:
# Example 3.2
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([[1],[2],[3],[4]])
torch.add(t1,t2, alpha=-1)

tensor([[ 0,  1,  2,  3],
        [-1,  0,  1,  2],
        [-2, -1,  0,  1],
        [-3, -2, -1,  0]])

This is how it works:

output = input (t1) + multiplier * other_tensor (t2)  
output[0][0] = t1[0] + (-1) * t2[0][0]  
output[0][1] = t1[1] (value 2) + (-1) * t2[1][0] (value 2)  



In [62]:
# Example 3.3 - breaking (to illustrate when it breaks)
t1 = torch.ones((5,2))
t2 = torch.ones((1,2,2))
torch.add(t1,t2)

RuntimeError: ignored

One of the most important consideration is that the tensors you are trying to add should be **broadcastable**. 

Here is some explanation on this
https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html


Closing comments about when to use this function

## Function 4 - matmul( tensor 1, tensor2, output_tensor optional) --> Tensor

This function performs multiplication of two tensors. The behaviour depends on the dimensionality of each tensor.

In [68]:
# Example 1 - working
t1 = torch.tensor([2,3])
t2 = torch.tensor([5,4])
t3 = torch.matmul(t1,t2)
t3

tensor(22)

2 * 5 + 3 * 4

In [76]:
# Example 2 - working
tensor1 = torch.tensor([[1,2,3,4],[5,6,7,8]])
tensor2 = torch.tensor([1,2,3,4])

torch.matmul(tensor1, tensor2)

tensor([30, 70])

Two tensors of dimensions 2 * 4 and 1 * 4 are multiplied using matmul. The result is 1 * 2 matrix.
First element : 1*1 + 2*2 + 3*3 + 4*4
Second Element: 5*1 + 6*2 + 7*3 + 8*4

In [83]:
# Example 3 - breaking (to illustrate when it breaks)
tensor1 = torch.tensor([[1,2,3,4],[5,6,7,8]])
tensor2 = torch.tensor([1,2,3])
torch.matmul(tensor1, tensor2)

RuntimeError: ignored

The above example does not work because there is a mismatch in dimensions. At least one dimension needs to match. 

The behavior is well explained on Torch documentation as below:

If both tensors are 1-dimensional, the dot product (scalar) is returned.

If both arguments are 2-dimensional, the matrix-matrix product is returned.

If the first argument is 1-dimensional and the second argument is 2-dimensional, a 1 is prepended to its dimension for the purpose of the matrix multiply. After the matrix multiply, the prepended dimension is removed.

If the first argument is 2-dimensional and the second argument is 1-dimensional, the matrix-vector product is returned.

If both arguments are at least 1-dimensional and at least one argument is N-dimensional (where N > 2), then a batched matrix multiply is returned. If the first argument is 1-dimensional, a 1 is prepended to its dimension for the purpose of the batched matrix multiply and removed after. If the second argument is 1-dimensional, a 1 is appended to its dimension for the purpose of the batched matrix multiple and removed after. The non-matrix (i.e. batch) dimensions are broadcasted (and thus must be broadcastable). For example, if input is a (j \times 1 \times n \times m)(j×1×n×m) tensor and other is a (k \times m \times p)(k×m×p) tensor, out will be an (j \times k \times n \times p)(j×k×n×p) tensor.

This is a utility function which I feel will be widely used in many applications. However, it's important to be cognizant of the dimensionality of each tensor.

## Function 5 - eq(t1,t2 or value, output optional) --> boolean Tensor

This function performs element by element comparison and returns a boolean tensor indicating results of the comparison.

In [84]:
# Example 1 - working
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1,2,3])
torch.eq(t1,t2)

tensor([True, True, True])

Compares each element from the first tensor to corresponding tensor from second element and constructs a boolean return matrix.

In [85]:
# Example 2 - working
t1 = torch.tensor([1,2,3])
torch.eq(t1,2)

tensor([False,  True, False])

Compares each element from the first tensor to the value of the second parameter and constructs a boolean return matrix.

In [86]:
# Example 3 - breaking (to illustrate when it breaks)
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1,2,3,4])
torch.eq(t1,t2)

RuntimeError: ignored

Since the dimensions of both tensors do not match, error is returned.

This function could be used to find mis-matches between two tensors.

## Conclusion

The above examples demonstrate some of the commonly used functions for tensor operations.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* Understanding array brodcasting in python : https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/Broadcasting.html

In [0]:
!pip install jovian --upgrade --quiet

In [0]:
import jovian

In [0]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
